services:
    flaskserver:
        build:
            context: .
            dockerfile: Dockerfile.flaskserver
        ports:
            - "80:80"
        command: ["python3", "server.py", "config/prod.json"]

    discordbot:
        build:
            context: .
            dockerfile: Dockerfile.discordbot
        command: ["python3", "bot.py", "config/prod.json"]
