FROM node:14
WORKDIR /app
COPY frontend/package.json frontend/package-lock.json ./
RUN npm install
ADD frontend .
EXPOSE 80
CMD ["npm", "start"]

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html