services:
    web:
        image: tbeidlershenk/web:latest
        build:
            context: .
            dockerfile: Dockerfile.web
        ports:
            - "5001:5001"
        volumes:
            - ./data:/app/data
            - ./config:/app/config
        command: ["python3", "src/server.py", "config/prod.json"]

    bot:
        image: tbeidlershenk/bot:latest
        build:
            context: .
            dockerfile: Dockerfile.bot
        volumes:
            - ./data:/app/data
            - ./config:/app/config
        command: ["python3", "src/bot.py", "config/prod.json"]
