services:
    flaskserver:
        build:
            context: .
            dockerfile: Dockerfile.flaskserver
        ports:
            - "5001:5001"
        command: ["python3", "server.py", "config/prod.json"]
        networks:
            - appnet

    discordbot:
        build:
            context: .
            dockerfile: Dockerfile.discordbot
        command: ["python3", "bot.py", "config/prod.json"]
        networks:
            - appnet

    reactapp:
        build:
            context: .
            dockerfile: Dockerfile.reactapp
        ports:
            - "80:80"
            - "443:443"
        networks:
            - appnet

networks:
    appnet:
        driver: bridge
