FROM node:lts-alpine as builder
WORKDIR /app
COPY frontend/package.json .
RUN npm install
ADD frontend .
RUN npm run build

FROM nginx:latest
COPY --from=builder /app/build /usr/share/nginx/html
COPY config/nginx.conf /etc/nginx/nginx.conf
EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]
