name: Build and Push Docker Images

on:
    push:
        branches:
            - main # Trigger the workflow when changes are pushed to the main branch
    pull_request:
        branches:
            - main # Trigger the workflow for pull requests targeting the main branch

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Log in to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Run Docker Buildx Build and Push
              run: |
                  docker buildx build --platform linux/amd64,linux/arm/v7,linux/arm64 -t tbeidlershenk/flaskserver:latest -f Dockerfile.flaskserver .
                  docker push tbeidlershenk/flaskserver:latest
                  docker buildx build --platform linux/amd64,linux/arm/v7,linux/arm64 -t tbeidlershenk/discordbot:latest -f Dockerfile.discordbot .
                  docker push tbeidlershenk/discordbot:latest
